version: '2'
services:
  db:
    image: postgres:9.5
  packs:
    build: .
    command: bash -c "cd assets && npm install && cd .. && mix deps.get && mix phx.server"
    volumes:
      - .:/basetest
    ports:
      - "4000:4000"
    depends_on:
      - db
